# Generated by Django 4.0 on 2021-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coin_symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Coin Sembolü')),
            ],
            options={
                'verbose_name': 'Kripto Para Sembolü',
                'verbose_name_plural': 'Kripto Para Sembolleri',
            },
        ),
    ]
